import type { Metadata } from 'next'

/**
 * DRAFT CONTENT -- not reviewed by a lawyer.
 *
 * Describes the Phase 1/2 architecture that does not exist yet (Supabase Auth
 * email accounts, Stripe Checkout, entitlements + usage counters). Nothing here
 * should claim a practice we do not actually follow -- re-read this when auth
 * and billing ship and correct anything that drifted.
 * See docs/MONETIZATION_ROADMAP.md Phase 0.
 */

export const metadata: Metadata = {
  title: 'Privacy Policy | CFB Team 360',
  description: 'What CFB Team 360 collects, why, and who it is shared with.',
}

const LAST_UPDATED = 'July 25, 2026'

export default function PrivacyPage() {
  return (
    <div className="p-8">
      <header className="mb-8">
        <h1 className="font-headline text-3xl text-[var(--text-primary)] underline-sketch inline-block">
          Privacy Policy
        </h1>
        <p className="text-sm text-[var(--text-muted)] mt-2">Last updated {LAST_UPDATED}</p>
      </header>

      <div className="max-w-3xl space-y-6 font-body text-[var(--text-secondary)] text-sm sm:text-base leading-relaxed">
        <section className="space-y-3">
          <p>
            The short version: we collect as little as we can get away with, we do not sell it, and
            the only third parties involved are the ones needed to sign you in, take payment, and
            keep the site running.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-headline text-xl text-[var(--text-primary)]">What we collect</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              <strong className="text-[var(--text-primary)] font-medium">Your email address</strong>,
              if you create an account. Sign-in uses a link emailed to you, so there is no password
              for us to store.
            </li>
            <li>
              <strong className="text-[var(--text-primary)] font-medium">Purchase records</strong> --
              which pass you bought and when it expires. Card details go to Stripe and never reach
              our servers.
            </li>
            <li>
              <strong className="text-[var(--text-primary)] font-medium">Usage counters</strong> --
              for example, how many assistant questions you have asked today, so we can enforce the
              limits described at checkout.
            </li>
            <li>
              <strong className="text-[var(--text-primary)] font-medium">Standard server logs</strong>{' '}
              generated by our hosting provider.
            </li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="font-headline text-xl text-[var(--text-primary)]">
            What we do with it
          </h2>
          <p>
            We use it to sign you in, to give you the access you paid for, to enforce usage limits,
            and to keep the site working. We do not sell your personal information, and we do not
            share it for advertising.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-headline text-xl text-[var(--text-primary)]">Who else is involved</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              <strong className="text-[var(--text-primary)] font-medium">Supabase</strong> --
              database and authentication.
            </li>
            <li>
              <strong className="text-[var(--text-primary)] font-medium">Stripe</strong> -- payment
              processing. Stripe handles your card data under its own privacy policy.
            </li>
            <li>
              <strong className="text-[var(--text-primary)] font-medium">Railway</strong> --
              application hosting.
            </li>
            <li>
              <strong className="text-[var(--text-primary)] font-medium">Anthropic</strong> -- if you
              use the assistant, your question and the relevant football data are sent to Anthropic&apos;s
              API to generate a response.
            </li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="font-headline text-xl text-[var(--text-primary)]">Retention</h2>
          <p>
            We keep account and purchase records while your account exists and for as long as needed
            for tax and accounting purposes afterward. Usage counters are short-lived.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-headline text-xl text-[var(--text-primary)]">Your choices</h2>
          <p>
            You can ask us to delete your account and the personal information attached to it; we may
            retain what the law requires us to keep. Depending on where you live, you may have
            additional rights to access, correct, or export your information. Contact us and we will
            honor them.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-headline text-xl text-[var(--text-primary)]">Children</h2>
          <p>
            The site is intended for users 18 and over and is not directed to children. We do not
            knowingly collect information from children.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-headline text-xl text-[var(--text-primary)]">Changes</h2>
          <p>
            If this policy changes materially, we will update the date above. Continued use after a
            change constitutes acceptance.
          </p>
        </section>
      </div>
    </div>
  )
}
